### ISSUE TITLE
Wont compile on Linux due to missing "intrin.h"

### ISSUE THREAD

**Issue by mark-orion** [paleajed/EWOCvj2#1]
I tried to build/compile on Linux (Ubuntu 18.04 LTS 64bit) and getting this error:
mark@alcyone:~/apps/src/EWOCvj2/linux/release$ make
g++ -DPACKAGE_NAME=\"EWOCvj2\" -DPACKAGE_TARNAME=\"ewocvj2\" -DPACKAGE_VERSION=\"2.00\" -DPACKAGE_STRING=\"EWOCvj2\ 2.00\" -DPACKAGE_BUGREPORT=\"paleajed@gmail.com\" -DPACKAGE_URL=\"\" -DHAVE_LIBOPENAL=1 -DHAVE_LIBRTMIDI=1 -DHAVE_LIBAVCODEC=1 -DHAVE_LIBAVDEVICE=1 -DHAVE_LIBAVFORMAT=1 -DHAVE_LIBAVUTIL=1 -DHAVE_LIBSWSCALE=1 -DHAVE_LIBGLUT=1 -DHAVE_LIBFREETYPE=1 -DHAVE_LIBX11=1 -DHAVE_LIBSDL2=1 -DHAVE_LIBGL=1 -DHAVE_LIBGLEW=1 -DHAVE_LIBJPEG=1 -DHAVE_LIBSNAPPY=1 -DHAVE_LIBBOOST_SYSTEM=1 -DHAVE_LIBBOOST_FILESYSTEM=1 -DHAVE_LIBGLIB_2_0=1 -DHAVE_LIBGOBJECT_2_0=1 -DHAVE_LIBGTK_3=1 -DHAVE_LIBNFD=1 -DHAVE_LIBLO=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_MALLOC_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE__BOOL=1 -DHAVE_PTRDIFF_T=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_MEMSET=1 -DPACKAGE=\"ewocvj2\" -DVERSION=\"2.00\" -I.  -DDATADIR=\"/usr/local/share/EWOCvj2\" -DFONTDIR=\"/usr/local/share/fonts/EWOCvj2\"   -std=c++17 -fpermissive -O3 -pthread -I/usr/include/rtmidi -I/usr/include/ffmpeg -I/usr/include/freetype2 -MT start.o -MD -MP -MF .deps/start.Tpo -c -o start.o ../../src/start.cpp
../../src/start.cpp:20:10: fatal error: intrin.h: No such file or directory
 #include <intrin.h>
          ^~~~~~~~~~
compilation terminated.
Makefile:452: recipe for target 'start.o' failed
make: *** [start.o] Error 1

**Comment by paleajed** [comment]
Good day,

I'll explain the situation.  I have been switching to Visual Studio
development the latest months, rendering all information about Linux
compilation redundant, meaning you can't use the current code on Linux.
Sorry for this mess, I will update the documentation on the GitHub site to
reflect the incomplete code state.
Good news is I am preparing a stable version for both Windows and Linux, to
be expected after some more weeks (or months if many problems would pop
up).  If you are interested, I could send you a mail when everything is in
place.  I had been spreading development versions during a certain time,
but these were in such a state they must have deterred a lot of people.
Not a good situation...

Your interest is much appreciated,

Gert De Roost

**Comment by mark-orion** [comment]
Gert,
thanks for your quick reply. Are you planning for this software to support the video4linux loopback device for output ? If so, then I am definitely interested as I am looking for a video mixing application that can stream its output to Linux desktop apps like Skype or Zoom.

**Comment by paleajed** [comment]
Mark,

I'll be looking into adding video4linux output, this should not be all too complex.

Gert.
